name: Build & Test

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Ubuntu Latest - GCC",
              artifact: "linux-gcc.tar.xz",
              os: ubuntu-latest,
              cc: "gcc-9",
              cxx: "g++-9",
            }
          - {
              name: "Ubuntu Latest - Clang",
              artifact: "linux-clang.tar.xz",
              os: ubuntu-latest,
              cc: "clang-9",
              cxx: "clang++-9",
            }

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: CMake Configure
        run: cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}

      - name: CMake Build
        run: mkdir build && cmake --build build

      - name: Run tests
        working-directory: ${{runner.workspace}}/build/test
        run: ./tests
